name: animalls
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  json_annotation: ^4.8.1
  loader_overlay: ^2.2.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
